version: "3"
services:
  www:
    image: "php:apache"
    volumes:
      - "./html:/var/www/html"
    ports:
      - "8889:80"
    depends_on:
      - db

  db:
    image: "mysql:latest"
    environment:
      - MYSQL_DATABASE=php_docker
      - MYSQL_USER=php_docker
      - MYSQL_PASSWORD=password
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - "./db:/docker-entrypoint-initdb.d"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8888:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
